"""Add auto_graded and grade_breakdown

Revision ID: 7a5e6e51434a
Revises:
Create Date: 2026-04-13 22:38:37.108878

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7a5e6e51434a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("auto_graded", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("grade_breakdown", sa.Text(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("submission", schema=None) as batch_op:
        batch_op.drop_column("grade_breakdown")
        batch_op.drop_column("auto_graded")

    # ### end Alembic commands ###
