"""
app/blueprints/admin.py

Lecturer request review + invite issuance (staff IDs are now generated
by the system in the LEC/SUB/YY/NNNNAA format — never typed in by an
admin, so they're guaranteed correct and collision-free), plus basic
user management (list + delete).
"""
from functools import wraps
from datetime import datetime

from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user

from app.extensions import db, limiter
from app.models import (
    LecturerAccessRequest, LecturerInviteCode, RequestStatus, Department,
    User, UserRole, Assignment, Submission, log_activity,
)
from app.utils.security import sanitize_input, valid_email_format
from app.utils.email import send_lecturer_invite_email

admin_bp = Blueprint('admin', __name__, url_prefix='/admin')


def admin_required(f):
    @wraps(f)
    @login_required
    def wrapper(*args, **kwargs):
        if not current_user.is_admin():
            flash('Admin access required.', 'danger')
            return redirect(url_for('dashboard.home'))
        return f(*args, **kwargs)
    return wrapper


# ==================== LECTURER ONBOARDING ====================
@admin_bp.route('/lecturer-requests')
@admin_required
def lecturer_requests():
    pending = (LecturerAccessRequest.query
               .filter_by(status=RequestStatus.PENDING)
               .order_by(LecturerAccessRequest.created_at.desc())
               .all())
    processed = (LecturerAccessRequest.query
                 .filter(LecturerAccessRequest.status != RequestStatus.PENDING)
                 .order_by(LecturerAccessRequest.reviewed_at.desc())
                 .limit(50).all())
    return render_template('admin/lecturer_requests.html', pending=pending, processed=processed)


@admin_bp.route('/lecturer-requests/<int:request_id>/approve', methods=['POST'])
@admin_required
@limiter.limit('20 per hour')
def approve_lecturer_request(request_id):
    req = LecturerAccessRequest.query.get_or_404(request_id)
    if req.status != RequestStatus.PENDING:
        flash('This request has already been processed.', 'warning')
        return redirect(url_for('admin.lecturer_requests'))

    req.status = RequestStatus.APPROVED
    req.reviewed_by = current_user.id
    req.reviewed_at = datetime.utcnow()

    # Staff ID is generated by the system (LEC/SUB/YY/NNNNAA) — never
    # typed in by an admin, so it's always correctly formatted.
    invite, plaintext_code = LecturerInviteCode.issue(
        email=req.email,
        department_id=req.department_id,
        issued_by_user_id=current_user.id,
        request_id=req.id,
    )
    log_activity(current_user.id, 'lecturer_request_approved', f'email={req.email}, staff_id={invite.staff_id}', request)
    db.session.commit()

    send_lecturer_invite_email(req.email, req.full_name, plaintext_code, invite.expires_at)
    flash(f'Approved. Staff ID {invite.staff_id} was generated and an invite code emailed to {req.email}.', 'success')
    return redirect(url_for('admin.lecturer_requests'))


@admin_bp.route('/lecturer-requests/<int:request_id>/reject', methods=['POST'])
@admin_required
def reject_lecturer_request(request_id):
    req = LecturerAccessRequest.query.get_or_404(request_id)
    if req.status != RequestStatus.PENDING:
        flash('This request has already been processed.', 'warning')
        return redirect(url_for('admin.lecturer_requests'))

    req.status = RequestStatus.REJECTED
    req.reviewed_by = current_user.id
    req.reviewed_at = datetime.utcnow()
    req.admin_notes = sanitize_input(request.form.get('reason', ''))[:500]
    log_activity(current_user.id, 'lecturer_request_rejected', f'email={req.email}', request)
    db.session.commit()

    flash('Request rejected.', 'success')
    return redirect(url_for('admin.lecturer_requests'))


@admin_bp.route('/lecturer-requests/invite-direct', methods=['POST'])
@admin_required
@limiter.limit('20 per hour')
def invite_lecturer_direct():
    """Skip the request step entirely — admin directly invites a known lecturer by email.
    Staff ID is system-generated, same as the approval path."""
    email = sanitize_input(request.form.get('email', '')).strip().lower()
    full_name = sanitize_input(request.form.get('full_name', '')).strip()
    department_id = request.form.get('department_id', type=int)

    if not email or not full_name:
        flash('Name and email are both required.', 'danger')
        return redirect(url_for('admin.lecturer_requests'))
    if not valid_email_format(email):
        flash('Please enter a valid email address.', 'danger')
        return redirect(url_for('admin.lecturer_requests'))

    invite, plaintext_code = LecturerInviteCode.issue(
        email=email, department_id=department_id, issued_by_user_id=current_user.id,
    )
    log_activity(current_user.id, 'lecturer_direct_invite', f'email={email}, staff_id={invite.staff_id}', request)
    db.session.commit()

    send_lecturer_invite_email(email, full_name, plaintext_code, invite.expires_at)
    flash(f'Staff ID {invite.staff_id} generated. Invite code sent to {email}.', 'success')
    return redirect(url_for('admin.lecturer_requests'))


# ==================== USER MANAGEMENT ====================
@admin_bp.route('/users')
@admin_required
def manage_users():
    role_filter = request.args.get('role', '')
    search = request.args.get('q', '').strip()

    query = User.query
    if role_filter in ('student', 'lecturer', 'admin'):
        query = query.filter_by(role=UserRole(role_filter))
    if search:
        like = f'%{search}%'
        query = query.filter(
            db.or_(User.name.ilike(like), User.email.ilike(like),
                   User.matric_number.ilike(like), User.staff_id.ilike(like))
        )

    users = query.order_by(User.created_at.desc()).limit(200).all()
    return render_template('admin/users.html', users=users, role_filter=role_filter, search=search)


@admin_bp.route('/users/<int:user_id>/delete', methods=['POST'])
@admin_required
@limiter.limit('20 per hour')
def delete_user(user_id):
    target = User.query.get_or_404(user_id)

    if target.id == current_user.id:
        flash("You can't delete your own account while logged in as it.", 'danger')
        return redirect(url_for('admin.manage_users'))

    if target.is_admin() and User.query.filter_by(role=UserRole.ADMIN).count() <= 1:
        flash('Cannot delete the only remaining admin account.', 'danger')
        return redirect(url_for('admin.manage_users'))

    # Hard-deleting someone with real academic history would destroy
    # grades and submitted work — refuse and point at deactivation
    # instead, which removes their access without erasing records.
    has_assignments = Assignment.query.filter_by(created_by=target.id).first() is not None
    has_submissions = Submission.query.filter_by(student_id=target.id).first() is not None
    if has_assignments or has_submissions:
        flash(
            f'{target.name} has existing assignments or submissions — deleting the account '
            'would destroy that academic history. Deactivate the account instead to remove '
            'their access while keeping records intact.',
            'danger'
        )
        return redirect(url_for('admin.manage_users'))

    confirm_email = request.form.get('confirm_email', '').strip().lower()
    if confirm_email != target.email.lower():
        flash('Email confirmation did not match — account was not deleted.', 'danger')
        return redirect(url_for('admin.manage_users'))

    log_activity(current_user.id, 'user_deleted',
                 f'Deleted user id={target.id}, email={target.email}, role={target.role.value}', request)
    db.session.delete(target)
    db.session.commit()

    flash(f'Account for {target.email} has been permanently deleted.', 'success')
    return redirect(url_for('admin.manage_users'))


@admin_bp.route('/users/<int:user_id>/toggle-active', methods=['POST'])
@admin_required
@limiter.limit('30 per hour')
def toggle_user_active(user_id):
    target = User.query.get_or_404(user_id)

    if target.id == current_user.id:
        flash("You can't deactivate your own account while logged in as it.", 'danger')
        return redirect(url_for('admin.manage_users'))

    target.is_active_account = not target.is_active_account
    if not target.is_active_account:
        target.deactivated_reason = 'Deactivated by admin.'
    else:
        target.deactivated_reason = None

    action = 'user_deactivated' if not target.is_active_account else 'user_reactivated'
    log_activity(current_user.id, action, f'user_id={target.id}, email={target.email}', request)
    db.session.commit()

    flash(f'{target.name} has been {"deactivated" if not target.is_active_account else "reactivated"}.', 'success')
    return redirect(url_for('admin.manage_users'))
